#20
ncedu-tlt/2018-dimi1-expense-manager pull request #20
Opened 2019-03-16 13:22 UTC by Nafanya123

Замена BigInteger на Integer во всех фаилах.
Теперь работает Delete.
Удаление и добавление аккаунтов работает через DataBaseWork.
Исправил надписи в модальных окнах.
При добавлении нового счета, ввод минимального баланса от 1.

2019-03-18 10:18 UTC, vifr0108 submitted a review, later dismissed
Ok

2019-03-20 07:38 UTC, dnsonin requested changes

2019-03-20 07:38 UTC, dnsonin commented on src/main/java/implementations/AccountsImpl.java
> -        }
Почему убрал проверку наличия расходов?
Расходы удаляются каскадно через primary, foreign key?

2019-03-20 07:48 UTC, dnsonin approved these changes

2019-03-21 08:26 UTC, vifr0108 approved these changes

2019-03-23 13:02 UTC, merged