Первые изменения
ncedu-tlt/2018-dimi1-expense-manager pull request #6
Opened 2019-02-18 12:17 UTC by torichay

Коллеги, проверьте, пожалуйста, код перед мержем

2019-02-18 12:20 UTC, dnsonin approved these changes
Approve

2019-02-18 14:05 UTC, vifr0108 approved these changes
Ok

2019-02-18 15:12 UTC, MasterSG63 approved these changes

2019-02-18 17:24 UTC, xgrisha approved these changes

2019-02-19 06:56 UTC, funruphp commented on src/main/java/com/netcracker/ncedu/tlt/dimi1/demo/IndexController.java
> +        model.addAttribute("persons", jdbcTemplate.queryForList("select * from person"));
Изменить,
перенести в метод getAllPersons()

2019-02-19 06:57 UTC, funruphp commented on src/main/java/com/netcracker/ncedu/tlt/dimi1/demo/IndexController.java
> +        model.addAttribute("accounts", jdbcTemplate.queryForList("select * from accounts"));
Изменить,
перенести в метод getAllAccounts()

2019-02-19 06:57 UTC, funruphp commented on src/main/java/com/netcracker/ncedu/tlt/dimi1/demo/IndexController.java
> +        model.addAttribute("budget_types", jdbcTemplate.queryForList("select * from budget_type"));
Изменить,
перенести в метод getAllBudgetTypes()

2019-02-19 06:57 UTC, funruphp commented on src/main/java/com/netcracker/ncedu/tlt/dimi1/demo/IndexController.java
> +        model.addAttribute("budgets", jdbcTemplate.queryForList("select * from budget"));
Изменить,
перенести в метод getAllBudgets()

2019-02-19 06:57 UTC, funruphp commented on src/main/java/com/netcracker/ncedu/tlt/dimi1/demo/IndexController.java
> +        model.addAttribute("plan_budgets", jdbcTemplate.queryForList("select * from plan_budget"));
Изменить,
перенести в метод getAllPlanBudgets()

2019-02-19 07:01 UTC, funruphp requested changes
Полин, привет, спасибо, за реквест.
Можно попросить строки(которые используются в контроллере для селекта из базы) отмеченные как 'изменить' вынести в класс например 'DatabaseWork' ?
И добавить метод 'getPersonByName'(извлечение из базы персоны по имени, для авторизации) тоже в 'DatabaseWork'.

Полин, если будут вопросы то пиши)

2019-02-20 16:52 UTC, funruphp approved these changes
ok

2019-02-21 13:55 UTC, merged